### ISSUE TITLE
Syntax error: PolymodFileSystem Expected ')'

### ISSUE THREAD

**Issue by MasterEric** [larsiusprime/polymod#108]
### Discussed in https://github.com/larsiusprime/polymod/discussions/107

<div type='discussions-op-text'>

<sup>Originally posted by **hafimiee** March  5, 2022</sup>
C:/HaxeToolkit/haxe/lib/polymod/1,5,2/polymod/fs/PolymodFileSystem.hx:19: characters 16-18 : Expected )</div>

**Comment by BoagerEpic301** [comment]
same

**Comment by MasterEric** [comment]
This is weird because I haven't reproduced it myself.

@BoagerEpic301 What version of Haxe are you using?

**Comment by MasterEric** [comment]
@hafimiee I'd also like to know your Haxe version to see if it's relevant to the issue.

**Comment by BoagerEpic301** [comment]
im using 4.1.5 for compiling kade engine

**Comment by BoagerEpic301** [comment]
nvm i just had to switch to 1.4.3 for it to compile correctly

**Comment by j0912345** [comment]
@MasterEric changing all occurrences of "is" to "==" in the if else statement fixes the error.
[PolymodFileSystem.zip](https://github.com/larsiusprime/polymod/files/8237049/PolymodFileSystem.zip)

**Comment by applerex** [comment]
`	public static function makeFileSystem(cls:Dynamic = null, params:PolymodFileSystemParams):IFileSystem
	{
		if (cls == null)
		{
			// We need to determine the class to instantiate.
			return _detectFileSystem(params);
		}
		else if ((cls is Class))
		{
			// Else, instantiate the provided class.
			return cast Type.createInstance(cls, [params]);
		}
		else
		{
			Polymod.error(BAD_CUSTOM_FILESYSTEM, "Passed an unknown type for a custom filesystem. Reverting to default...");
			return makeFileSystem(null, params);
		}
	}`

**Comment by applerex** [comment]
> 	public static function makeFileSystem(cls:Dynamic = null, params:PolymodFileSystemParams):IFileSystem
	{
		if (cls == null)
		{
			// We need to determine the class to instantiate.
			return _detectFileSystem(params);
		}
		else if ((cls is Class))
		{
			// Else, instantiate the provided class.
			return cast Type.createInstance(cls, [params]);
		}
		else
		{
			Polymod.error(BAD_CUSTOM_FILESYSTEM, "Passed an unknown type for a custom filesystem. Reverting to default...");
			return makeFileSystem(null, params);
		}
	}

**Comment by Wo0fle** [comment]
> 

You had to switch all the way from 4.1.5 to 1.4.3?????

Did you mean 4.1.3???

**Comment by MasterEric** [comment]
Sorry I've been so busy, just posted a 1.5.3 with some minor fixes I've been working on, including a proper one for this issue.

**Comment by hayfii** [comment]
> @hafimiee I'd also like to know your Haxe version to see if it's relevant to the issue.

Sorry for a very late reply, it's the latest version of Haxe, I didn't saw any notifications.
