### ISSUE TITLE
Arbitrary virtual filesystems

### ISSUE THREAD

**Issue by larsiusprime** [larsiusprime/polymod#12]
Right now Polymod loads all user mods from an on-disk filesystem through sys.io.File / sys.FileSystem commands.

Fortunately, this is abstracted through calls to PolymodFileSystem, which means we can add arbitrary new virtual file systems in the future. We should probably wait for an actual user case to present itself before doing a bunch of speculative stuff, but I can imagine that users might want to be able to provide mods in the form of e.g. a single ZIP or PAK file. This might be the only way to support mods in environments that can receive a single blob of user data somehow, but don't have arbitrary access to an on-disk file system.

- [ ] OpenFLBackend: make sure load<X> calls properly go through PolymodFileSystem
- [ ] Add ability to define new PolymodFileSystem backends & switch between them

**Comment by sh-dave** [comment]
I actually already need a way for the `backend` to decide what filesystem should be used for the implementation of the Kha backend. In my test code i wrote an [electron based one](https://github.com/sh-dave/polymod-kha/blob/master/polymod/fs/ElectronFileSystem.hx) as this is Kha's current main development target. I've seen there is `polymod.fs.PolymodFileSystem` and `Polymod.getFileSystem()` now, but the latter one is unused?

**Comment by larsiusprime** [comment]
Yeah, the latter is cruft left over from a refactor, and it's a private function anyway. Probably what I want is for PolymodFilesystem to be an abstract call that falls through to whatever the "true" filesystem is. Right now it's hardcoded to sys, but we could make it configurable by the user on init.

**Comment by MasterEric** [comment]
This is resolved by #34 (which lets uses provide their own file system interface class). I am looking into possibly adding a standard implementation of ZipFileSystem though (because adding and removing mods as single archives is a bit more idiot-proof).

**Comment by MasterEric** [comment]
This was resolved in Polymod v1.1.
