### ISSUE TITLE
Support binary appending / merging

### ISSUE THREAD

**Issue by larsiusprime** [larsiusprime/polymod#13]
This might be useful, but I'll wait for an actual user to show up with a specific use case before giving it a go.

The basic idea is that the user will have to provide all the rules to fulfill binary file format appending and merging. They'll specify:

- A file extension that signifies a particular file format
- A callback `append(baseBytes:Bytes,appendBytes:Bytes)` for appending
- A callback `merge(baseBytes:Bytes,mergeBytes:Bytes)` for merging

In the case of merging, it will be up to the user to provide all the parsing and pattern matching / payload injection logic in their callbacks.

**Comment by MasterEric** [comment]
I haven't personally found a use case for this feature. If somebody comes along and makes a good case for it, I can look into providing an implementation for it.

**Comment by larsiusprime** [comment]
I vote YAGNI for now and close the feature unless someone asks for it.

**Comment by MasterEric** [comment]
> I vote YAGNI for now and close the feature unless someone asks for it.

Agreed.
