### ISSUE TITLE
cannot compile

### ISSUE THREAD

**Issue by ItsyourboyJonnycat** [larsiusprime/polymod#134]
![Screen Shot 2022-08-27 at 2 34 41 PM](https://user-images.githubusercontent.com/107599365/187048828-804a6442-1569-48b4-878a-a1005db8e707.png)

**Comment by ItsyourboyJonnycat** [comment]
nvm i fixed it puting this <haxedef name="hscriptPos" value="true" />

**Comment by RoseShineCJGamingYT** [comment]
Can you help me fix this?
