### ISSUE TITLE
hscript.Interp has no field setVar

### ISSUE THREAD

**Issue by TheRealJake12** [larsiusprime/polymod#150]
![image](https://user-images.githubusercontent.com/84357907/212772966-64bbedda-b572-4393-8812-7eaaf32dbac5.png)

(using a slightly edited version of FNF Modcore)

**Comment by TheRealJake12** [comment]
also, I "fixed" it by editing the file to work. Basically removing the functions that broke.

**Comment by AltronMaxX** [comment]
I think that could be fixed by reinstalling polymod and hscript

**Comment by EliteMasterEric** [comment]
The solution to this bug is to install the CORRECT version of the `hscript` haxelib (which is 2.5.0). You likely have 2.4.0 installed.

**Comment by TheRealJake12** [comment]
yeah hscript 2.5.0 and polymod 1.7.0 are installed. I still have the issue.

**Comment by TheRealJake12** [comment]
> yeah hscript 2.5.0 and polymod 1.7.0 are installed. I still have the issue.

I love it when I don't realize I have hscript.Interp overriden with my own custom file in source code. Sorry Eric. I was uptodate though.
