### ISSUE TITLE
[BUG] pathName parameter for scripted functions is ignored

### ISSUE THREAD

**Issue by AltronMaxX** [larsiusprime/polymod#153]
As described [here](https://github.com/larsiusprime/polymod/blob/master/docs/docs/scripting.markdown), this parameter allows you to call a function from a file that is not named as the function itself. I`ve done it (picture 1), but hscript is still looking for the buildCallbacks file (picture 2). I also attach a view of the getScriptPath function (picture 3).
![image](https://user-images.githubusercontent.com/75096038/213353979-2e18d5cf-ad13-4096-89df-ad85f2f53700.png)
![image](https://user-images.githubusercontent.com/75096038/213354175-27fe4286-ed7e-432f-9018-ceac41e7c0c6.png)
![image](https://user-images.githubusercontent.com/75096038/213354301-5e79391d-0954-4dc6-8650-9b3ff980d56a.png)

**Comment by MasterEric** [comment]
I haven't stress-tested the scripted functions system in a while, I've mainly been using the scripted classes system since I built it last year.

Will try to reproduce and fix this, this seems like a legitimate bug that needs fixing.

**Comment by MasterEric** [comment]
@AltronMaxX Wouldn't it have tried to find the script `notes/` then?

**Comment by AltronMaxX** [comment]
It tried to find buildCallbacks in that folder.
