### ISSUE TITLE
[BUG] Custom Audio does not work

### ISSUE THREAD

**Issue by gamerbross** [larsiusprime/polymod#160]
(I'm using the flixel/lime framework)

I set `""` to `assetPrefix` to create an `assets` folder in the mod, and the mod audio stopped working. I don't know if it's just the audio, but nothing else stopped working.

I tried to solve it and see what caused it, but I didn't come to a conclusion. I just managed to notice that instead of finding the audio file with the type `AUDIO_GENERIC` and `AUDIO_SOUND`, it only finds the type `AUDIO_GENERIC`.

(`assetPrefix` set to `""`)
![image](https://user-images.githubusercontent.com/55158797/224131802-9de0f3e1-d248-4f2f-958e-b43f8539947b.png)
![image](https://user-images.githubusercontent.com/55158797/224131819-042e47a4-fa0a-4d38-a0e0-953da7775a94.png)

(`assetPrefix` set to `"assets/"` (default))
![image](https://user-images.githubusercontent.com/55158797/224131365-cd41305f-66e8-4ff4-9a65-38895fef647a.png)
![image](https://user-images.githubusercontent.com/55158797/224131381-b3af7345-a275-4067-b511-1e813661ce43.png)

I tried using the `extensionMap` parameter to override and always use the `AUDIO_SOUND` type and the parameter doesn't work (in any way). #159

## UPDATE
I fixed this issue in this pull request: #162

**Comment by AltronMaxX** [comment]
But why would you create an assets folder inside the mods folder?

**Comment by gamerbross** [comment]
> But why would you create an assets folder inside the mods folder?

to better organize the mod files
