### ISSUE TITLE
Small issue

### ISSUE THREAD

**Issue by Joalor64GH** [larsiusprime/polymod#181]
I'm testing out polymod for modding support, but for some reason, audio file replacement isn't working??
Can it even replace audio files or is it just something that needs to be fixed?

**Comment by EliteMasterEric** [comment]
It should be able to replace any binary asset. You'd need to give more information about your setup for me to be able to help you.

**Comment by Joalor64GH** [comment]
Well, I think it might have something to do with this.
```hx
public static function returnSound(key:String, ?cache:Bool = true):Sound {
		if (Assets.exists(file('$key.ogg'), SOUND)) {
			var path:String = file('$key.ogg');
			if (!currentTrackedSounds.exists(path))
				currentTrackedSounds.set(path, Assets.getSound(path, cache));

			localTrackedAssets.push(path);
			return currentTrackedSounds.get(path);
		}

		trace('oops! $key returned null');
		return null;
	}
	```

**Comment by Joalor64GH** [comment]
Nevermind, it works! It was just an issue with my mod handler.
