### ISSUE TITLE
I can't install pylomod using haxelib

### ISSUE THREAD

**Issue by NixxdeOfficial** [larsiusprime/polymod#22]
I am making a Friday Night Funkin' mod and I need to install pylomod to compile it but it doesn't work.
It shows this error:

`Error: Failed with error: No such Project : polymod`

And when I try to compile it anyways, it shows this error:

`Error: Could not find haxelib "polymod", does it need to be installed?`

Thanks

**Comment by RafaelLegal** [comment]
I **also** have this issue.

**Comment by YupamUzuink** [comment]
if i use the command "haxelib git polymod" on command prompt
they say:
`Error: Could not use git, please make sure it is installed and available in your PATH.` 
and if i use the command "haxelib search polymod" on command prompt
they say:
`0 libraries found`

**Comment by DaBlueNinja03** [comment]
also! you have to make sure you are not running the command prompt  as an administrator also, you have to type `haxelib git polymod https://github.com/larsiusprime/polymod.git`

**Comment by MasterEric** [comment]
This will be resolved soon by uploading Polymod to Haxelib.

**Comment by MasterEric** [comment]
You can now run `haxelib install polymod` to [download the Polymod Haxelib](https://lib.haxe.org/p/polymod/).
