### ISSUE TITLE
not working with different library paths

### ISSUE THREAD

**Issue by Hendicted** [larsiusprime/polymod#24]
is there a reason why the libraries dont work with it and cant find the modded in files? it works on the normal images folder but not on different libraries

**Comment by Hendicted** [comment]
nevermind it had something to do with the way the game calls the assets

**Comment by MasterEric** [comment]
This is resolved by the `funkinfixes` branch, but there is a bug with it that is resolved in my fork: https://github.com/MasterEric/polymod

**Comment by MasterEric** [comment]
This is fully implemented in Polymod v1.3, better documentation coming soon.
