### ISSUE TITLE
Need error handling & line numbers around script loading / parsing

### ISSUE THREAD

**Issue by jcward** [larsiusprime/polymod#8]
An hscript with a syntax error crashes the app, and doesn't even report line / position / filenames:

```
Called from Demo::new line 81
Called from polymod.hscript.ScriptRunner::load line 23
Called from polymod.hscript.Script::$init line 41
Called from a C function
Called from polymod.hscript.Script::new line 54
Called from hscript.Parser::parseString line 181
Called from hscript.Parser::parse line 192
Called from hscript.Parser::parseFullExpr line 294
Called from hscript.Parser::parseExpr line 357
Called from hscript.Parser::parseExprNext line 724
Called from hscript.Parser::parseExprList line 913
Called from hscript.Parser::unexpected line 198
Uncaught exception - EUnexpected(;)
```

HScript can be compiled with line numbers enabled, if I recall. Perhaps do that when in `-debug` mode? Or perhaps always (in a released product, modders will probably want script debug info?)

**Comment by larsiusprime** [comment]
Good point!

You know, we should probably make ALL the hscript settings configurable somehow. Maybe have a static class in Polymod like HScriptSettings that the macro can crawl over? I'm wondering how you'd set that up though... 

But however its implemented, we should expose settings like this, and whether variable types are allowed or not (something people will want if they're refactoring existing functions out into script files, so they don't have to go back in and delete all the typing), etc.

**Comment by MasterEric** [comment]
With Polymod v1.3, HScript line numbers (required for proper error reporting) are now enabled in debug builds.

If you want to enable line numbers for yourself in release builds, follow the method for your system:
* For Lime, add `<haxedef name="hscriptPos" value="true" />` to your `project.xml`.
* For other haxe builds, add `-D hscriptPos` to your `hxml` file.
