### ISSUE TITLE
Abstracts cannot be passed as constants

### ISSUE THREAD

**Issue by DotWith** [larsiusprime/polymod#80]
Error Log: ```C:/HaxeToolkit/haxe/lib/polymod/git/polymod/hscript/HScriptMacro.hx:258: characters 44-50 : Cannot use abstract as value```

**Comment by MasterEric** [comment]
For context, @DotWith was attempting to pass FlxColor as a value.

However, FlxColor cannot be passed to the HScript at runtime for a simple reason; FlxColor doesn't exist.

To clarify, FlxColor is not a class; it is an [abstract type](https://haxe.org/manual/types-abstract.html), which wraps the `Int` class. At runtime, all instances of FlxColor are replaced inline with `Int` values and FlxColor is basically scrubbed from existance.

One possible workaround could be to define your own static class which includes these values; this would create a constant identifier you could pass to your context.
