### ISSUE TITLE
[Some sort of Enhancement?] implement an automated reader of folders in assets

### ISSUE THREAD

**Issue by Cheemsandfriends** [larsiusprime/polymod#85]
Hello!
I know it sounds kinda stupid but, it would be great that there should be a reader of folder in assets to have and that would be the assetlibrarypaths in case that the person who uses Polymod and is lazy, doesn't have to insert the folder manually one by one

**Comment by MasterEric** [comment]
I don't understand the prompt.

Adding support for additional asset libraries (a planned feature now btw) would require defining them manually. If you automatically added new asset libraries based on the folder names, it would break mods trying to replace default assets.

Additionally, having assets automatically split into separate libraries would be confusing for developers who are only using one asset library.

**Comment by Cheemsandfriends** [comment]
@MasterEric, I know that additional asset libraries are a feature that is planned, but there is something that I can't take and it's adding several folder names if you have like a ton. I thought that just reading the folder names if the dev doesn't want to add some stuff sounded like a nice idea!
So like it's the name of the folder and the dir would add at the beginning `./` cos it's the main thing.

Idk maybe it's not a good idea.
