### ISSUE TITLE
the new polymod crashes on macos 

### ISSUE THREAD

**Issue by ThatDisabledKid** [larsiusprime/polymod#86]
i am a mac porter and when i fully build the game for fnf it crashes instantly when i try to open the application and its the same for the kade engine loading screen

**Comment by JonnyboyTheboy** [comment]
this is what i get when i try to open the polymod zsh: segmentation fault  

Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[Process completed]

**Comment by MasterEric** [comment]
Hey @JonnyboyTheboy,

This is a support forum for Polymod, not Kade Engine or Friday Night Funkin. We can continue to evaluate this issue but only if you can assert the issue is in fact due to Polymod.

The best way to prove this is to test using the sample projects included in this repository.
