### ISSUE TITLE
I got this error when I try to build it for fnf 

### ISSUE THREAD

**Issue by ThatDisabledKid** [larsiusprime/polymod#92]
/usr/local/lib/haxe/lib/polymod/git/polymod/backends/FlixelBackend.hx:50: characters 25-30 : openfl.utils.IAssetCache has no field cache

**Comment by MrClogsworthYT** [comment]
this isnt the fnf repo

**Comment by MasterEric** [comment]
> this isnt the fnf repo

Normally I would agree and close this, but the issue is definitely with this repo. There's a syntax error in the newly released 1.4.0 that prevents compiling.

**Comment by MrClogsworthYT** [comment]
> > this isnt the fnf repo
> 
> Normally I would agree and close this, but the issue is definitely with this repo. There's a syntax error in the newly released 1.4.0 that prevents compiling.

then just install an old version of polymod -_-

**Comment by MasterEric** [comment]
Version 1.4.1 just got pushed so this should be fixed.
